/**
 * Tests for internal links across all markdown content files.
 *
 * Checks two categories of links:
 *   1. Standard Markdown links  [label](relative/path)  that point to local files.
 *   2. Obsidian-style wikilinks  [[filename]]  that should resolve to a markdown
 *      file somewhere in the repository (Quartz "shortest path" resolution).
 *
 * External links (http/https/mailto/tel), tag pages generated by Quartz
 * (paths containing /tags/), and links to assets such as images and PDFs
 * are explicitly excluded from validation.
 */
import { existsSync, readFileSync, readdirSync, statSync } from "fs"
import {
  basename,
  dirname,
  extname,
  join,
  normalize,
  relative,
  resolve,
} from "path"
import { describe, expect, it } from "vitest"

const REPO_ROOT = join(import.meta.dirname, "..")

/** File extensions that should not be validated as markdown targets. */
const ASSET_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".svg",
  ".webp",
  ".pdf",
  ".ico",
  ".mp4",
  ".mp3",
])

/** Directories to skip when building the file index. */
const SKIP_DIRS = new Set([".git", ".obsidian", "node_modules"])

/** Paths (relative to REPO_ROOT) to exclude from link validation. */
const EXCLUDED_FROM_LINK_CHECK = new Set([
  "README.md",
  "assets/_templates/Page.md",
  "assets/_templates/News.md",
])

// ---------------------------------------------------------------------------
// File index helpers
// ---------------------------------------------------------------------------

/** Recursively list all files under a directory. */
function listAllFiles(dir: string): string[] {
  const results: string[] = []
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry)
    const relPath = relative(REPO_ROOT, fullPath)
    if (entry.startsWith(".") || SKIP_DIRS.has(relPath)) continue
    const stat = statSync(fullPath)
    if (stat.isDirectory()) {
      results.push(...listAllFiles(fullPath))
    } else {
      results.push(fullPath)
    }
  }
  return results
}

/** All markdown files in the repo, as absolute paths. */
const allMarkdownFiles = listAllFiles(REPO_ROOT).filter(
  (f) => extname(f) === ".md",
)

/**
 * Map from lower-cased base-name (without extension) to the list of absolute
 * paths that share that name.  Used to resolve wikilinks via shortest-path.
 */
const wikilinkIndex = new Map<string, string[]>()
for (const f of allMarkdownFiles) {
  const key = basename(f, ".md").toLowerCase()
  const existing = wikilinkIndex.get(key) ?? []
  existing.push(f)
  wikilinkIndex.set(key, existing)
}

// ---------------------------------------------------------------------------
// Link extraction helpers
// ---------------------------------------------------------------------------

/**
 * Extracts relative Markdown links from a document body (after frontmatter).
 * Returns `{ raw, resolved }` pairs where `resolved` is the absolute path to
 * check for existence.
 *
 * Skips:
 *  - External URLs (http/https/mailto/tel)
 *  - Absolute site paths (starting with /)
 *  - Fragment-only links (#)
 *  - Quartz tag page paths (containing /tags/)
 *  - Asset file extensions handled elsewhere
 */
function extractMarkdownLinks(
  body: string,
  fileDir: string,
): Array<{ raw: string; resolved: string }> {
  const results: Array<{ raw: string; resolved: string }> = []
  // Matches [text](path) but not ![image](path)
  const re = /(?<!!)\[[^\]]*\]\(([^)]+)\)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(body)) !== null) {
    let href = m[1].split(" ")[0] // strip optional title in quotes after space
    href = href.split("#")[0].trim() // strip fragment
    if (!href) continue
    if (/^(https?:|mailto:|tel:|\/\/)/.test(href)) continue
    if (href.startsWith("/")) continue
    if (href.includes("/tags/")) continue

    // URL-decode percent-encoded characters
    const decoded = decodeURIComponent(href)
    const ext = extname(decoded)
    if (ASSET_EXTENSIONS.has(ext.toLowerCase())) continue

    // Resolve against the directory of the current file
    let resolved = resolve(fileDir, decoded)
    // If there is no extension, try appending .md or /index.md
    if (!extname(resolved)) {
      if (existsSync(resolved + ".md")) {
        resolved = resolved + ".md"
      } else if (existsSync(join(resolved, "index.md"))) {
        resolved = join(resolved, "index.md")
      }
    }

    results.push({ raw: m[1], resolved: normalize(resolved) })
  }
  return results
}

/**
 * Extracts Obsidian wikilinks from a document body.
 * Returns the target slug (path part before `|` and `#`).
 *
 * Skips links to asset file types.
 */
function extractWikilinks(body: string): string[] {
  const results: string[] = []
  const re = /\[\[([^\]]+)\]\]/g
  let m: RegExpExecArray | null
  while ((m = re.exec(body)) !== null) {
    // [[path#heading|display]] → keep only the path
    const target = m[1].split("|")[0].split("#")[0].trim()
    if (!target) continue
    const ext = extname(target).toLowerCase()
    if (ASSET_EXTENSIONS.has(ext)) continue
    results.push(target)
  }
  return results
}

/**
 * Resolves a wikilink target to an absolute path using Quartz's
 * "shortest path" algorithm:
 *  - If the target contains `/`, treat it as a path relative to REPO_ROOT.
 *  - Otherwise search by base-name across all markdown files.
 *
 * Returns `null` when no matching file can be found.
 */
function resolveWikilink(target: string): string | null {
  if (target.includes("/")) {
    const candidate = join(REPO_ROOT, target + ".md")
    if (existsSync(candidate)) return candidate
    const indexCandidate = join(REPO_ROOT, target, "index.md")
    if (existsSync(indexCandidate)) return indexCandidate
    return null
  }
  const matches = wikilinkIndex.get(target.toLowerCase())
  if (matches && matches.length > 0) return matches[0]
  return null
}

// ---------------------------------------------------------------------------
// Strip frontmatter from a file so links inside YAML are not validated.
// ---------------------------------------------------------------------------
function stripFrontmatter(content: string): string {
  if (!content.startsWith("---")) return content
  const end = content.indexOf("---", 3)
  if (end === -1) return content
  return content.slice(end + 3)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("Internal link integrity", () => {
  describe("standard Markdown links", () => {
    it("all relative links resolve to existing files", () => {
      const broken: string[] = []

      for (const file of allMarkdownFiles) {
        if (EXCLUDED_FROM_LINK_CHECK.has(relative(REPO_ROOT, file))) continue
        const body = stripFrontmatter(readFileSync(file, "utf-8"))
        const links = extractMarkdownLinks(body, dirname(file))
        for (const { raw, resolved } of links) {
          if (!existsSync(resolved)) {
            broken.push(`${relative(REPO_ROOT, file)}: [link](${raw}) → ${relative(REPO_ROOT, resolved)}`)
          }
        }
      }

      expect(
        broken,
        `Broken relative Markdown links:\n  ${broken.join("\n  ")}`,
      ).toHaveLength(0)
    })
  })

  describe("Obsidian wikilinks", () => {
    it("all wikilinks resolve to existing markdown files", () => {
      const broken: string[] = []

      for (const file of allMarkdownFiles) {
        if (EXCLUDED_FROM_LINK_CHECK.has(relative(REPO_ROOT, file))) continue
        const body = stripFrontmatter(readFileSync(file, "utf-8"))
        const targets = extractWikilinks(body)
        for (const target of targets) {
          const resolved = resolveWikilink(target)
          if (!resolved) {
            broken.push(`${relative(REPO_ROOT, file)}: [[${target}]]`)
          }
        }
      }

      expect(
        broken,
        `Unresolvable wikilinks:\n  ${broken.join("\n  ")}`,
      ).toHaveLength(0)
    })
  })
})
